services:
  - type: web
    name: hisabpro
    runtime: python
    buildCommand: "./start.sh"
    startCommand: "gunicorn app.main:app -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: sqlite:///./sales_manager.db
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
